import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/**
 * Seed data (ARB-013).
 *
 * Idempotent by construction: every statement is an upsert keyed on the natural key, so
 * running the seed against a populated database restores the intended values rather than
 * duplicating or failing. Nothing here deletes.
 */
const SEED_DIR = fileURLToPath(new URL('../seed/', import.meta.url));

export interface ServiceCategorySeed {
  readonly slug: string;
  readonly name: string;
  /** The owner's decision (docs/02 D-04); false until they make it. */
  readonly inHouse?: boolean;
}

export interface MarketPriceBandSeed {
  readonly categorySlug: string;
  readonly currency: string;
  readonly p25Minor: number;
  readonly p50Minor: number;
  readonly p75Minor: number;
  readonly sampleSize?: number;
}

function readSeedFile<T>(name: string): T {
  return JSON.parse(readFileSync(`${SEED_DIR}${name}`, 'utf8')) as T;
}

export function loadServiceCategories(): ServiceCategorySeed[] {
  return readSeedFile<{ categories: ServiceCategorySeed[] }>('service-categories.json').categories;
}

export function loadMarketPriceBands(): MarketPriceBandSeed[] {
  const file = readSeedFile<{ currency: string; bands: Partial<MarketPriceBandSeed>[] }>(
    'market-price-bands.json',
  );
  return file.bands.map((band) => ({
    categorySlug: band.categorySlug ?? '',
    currency: band.currency ?? file.currency,
    p25Minor: band.p25Minor ?? 0,
    p50Minor: band.p50Minor ?? 0,
    p75Minor: band.p75Minor ?? 0,
    sampleSize: band.sampleSize ?? 0,
  }));
}

function quote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/**
 * The whole seed as one SQL script. Ordering matters: bands reference a category slug,
 * so the taxonomy is written first.
 */
export function buildSeedSql(): string {
  const categories = loadServiceCategories();
  const bands = loadMarketPriceBands();

  const lines: string[] = [
    '-- Generated by packages/db/src/seed.ts. Edit the JSON in packages/db/seed/, not this file.',
    'begin;',
  ];

  for (const [index, category] of categories.entries()) {
    lines.push(
      `insert into service_categories (slug, name, in_house, sort_order)`,
      `values (${quote(category.slug)}, ${quote(category.name)}, ${category.inHouse ?? false}, ${index})`,
      // in_house is deliberately not overwritten: once the owner ticks a category, a
      // later seed run must not quietly untick it.
      `on conflict (slug) do update set name = excluded.name, sort_order = excluded.sort_order;`,
    );
  }

  for (const band of bands) {
    lines.push(
      `insert into market_price_bands (category_slug, currency, p25_minor, p50_minor, p75_minor, sample_size, source)`,
      `values (${quote(band.categorySlug)}, ${quote(band.currency)}, ${band.p25Minor}, ${band.p50Minor}, ${band.p75Minor}, ${band.sampleSize ?? 0}, 'seed')`,
      `on conflict (category_slug, currency, source) do update set`,
      `  p25_minor = excluded.p25_minor, p50_minor = excluded.p50_minor,`,
      `  p75_minor = excluded.p75_minor, sample_size = excluded.sample_size;`,
    );
  }

  lines.push('commit;', '');
  return lines.join('\n');
}
