import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { validatePlan, type Plan } from '@arbitron/core';

/**
 * Seed data (ARB-013).
 *
 * Idempotent by construction: every statement is an upsert keyed on the natural key, so
 * running the seed against a populated database restores the intended values rather than
 * duplicating or failing. Nothing here deletes.
 */
const SEED_DIR = fileURLToPath(new URL('../seed/', import.meta.url));

export interface ServiceCategorySeed {
  readonly slug: string;
  readonly name: string;
  /** The owner's decision (docs/02 D-04); false until they make it. */
  readonly inHouse?: boolean;
}

export interface MarketPriceBandSeed {
  readonly categorySlug: string;
  readonly currency: string;
  readonly p25Minor: number;
  readonly p50Minor: number;
  readonly p75Minor: number;
  readonly sampleSize?: number;
}

function readSeedFile<T>(name: string): T {
  return JSON.parse(readFileSync(`${SEED_DIR}${name}`, 'utf8')) as T;
}

export function loadServiceCategories(): ServiceCategorySeed[] {
  return readSeedFile<{ categories: ServiceCategorySeed[] }>('service-categories.json').categories;
}

export function loadMarketPriceBands(): MarketPriceBandSeed[] {
  const file = readSeedFile<{ currency: string; bands: Partial<MarketPriceBandSeed>[] }>(
    'market-price-bands.json',
  );
  return file.bands.map((band) => ({
    categorySlug: band.categorySlug ?? '',
    currency: band.currency ?? file.currency,
    p25Minor: band.p25Minor ?? 0,
    p50Minor: band.p50Minor ?? 0,
    p75Minor: band.p75Minor ?? 0,
    sampleSize: band.sampleSize ?? 0,
  }));
}

/**
 * The plans on sale (ARB-410): each checked by `validatePlan` before it is written, so a
 * plan with a limit left out never reaches the database. The file ships empty until the
 * owner decides the pricing (docs/02 D-12).
 */
/**
 * The grace period after a failed payment, in days (ARB-420, D-070): the owner's, from
 * plans.json, and null until chosen.
 */
export function loadGraceDays(input?: unknown): number | null {
  const file = (input ?? readSeedFile<unknown>('plans.json')) as { graceDays?: unknown };
  const days = file?.graceDays ?? null;
  if (days === null) return null;
  if (typeof days !== 'number' || !Number.isInteger(days) || days < 0) {
    throw new Error('plans.json graceDays must be a whole number of days, 0 or more, or null');
  }
  return days;
}

export function loadPlans(input?: unknown): Plan[] {
  const file = (input ?? readSeedFile<unknown>('plans.json')) as { plans?: unknown };
  if (!Array.isArray(file?.plans)) throw new Error('plans.json must hold a "plans" list');
  const codes = new Set<string>();
  return file.plans.map((raw, index) => {
    const result = validatePlan(raw);
    if (!result.ok) {
      const problems = result.errors.map((e) => `${e.field} ${e.message}`).join('; ');
      throw new Error(`plans.json plan ${String(index + 1)}: ${problems}`);
    }
    if (codes.has(result.value.code)) {
      throw new Error(
        `plans.json plan ${String(index + 1)}: code ${result.value.code} is used twice`,
      );
    }
    codes.add(result.value.code);
    return result.value;
  });
}

function quote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/**
 * The whole seed as one SQL script. Ordering matters: bands reference a category slug,
 * so the taxonomy is written first.
 */
export function buildSeedSql(
  options: { readonly plans?: readonly Plan[]; readonly graceDays?: number | null } = {},
): string {
  const categories = loadServiceCategories();
  const bands = loadMarketPriceBands();
  const plans = options.plans ?? loadPlans();
  const graceDays = options.graceDays === undefined ? loadGraceDays() : options.graceDays;

  const lines: string[] = [
    '-- Generated by packages/db/src/seed.ts. Edit the JSON in packages/db/seed/, not this file.',
    'begin;',
  ];

  for (const [index, category] of categories.entries()) {
    lines.push(
      `insert into service_categories (slug, name, in_house, sort_order)`,
      `values (${quote(category.slug)}, ${quote(category.name)}, ${category.inHouse ?? false}, ${index})`,
      // in_house is deliberately not overwritten: once the owner ticks a category, a
      // later seed run must not quietly untick it.
      `on conflict (slug) do update set name = excluded.name, sort_order = excluded.sort_order;`,
    );
  }

  for (const band of bands) {
    lines.push(
      `insert into market_price_bands (category_slug, currency, p25_minor, p50_minor, p75_minor, sample_size, source)`,
      `values (${quote(band.categorySlug)}, ${quote(band.currency)}, ${band.p25Minor}, ${band.p50Minor}, ${band.p75Minor}, ${band.sampleSize ?? 0}, 'seed')`,
      `on conflict (category_slug, currency, source) do update set`,
      `  p25_minor = excluded.p25_minor, p50_minor = excluded.p50_minor,`,
      `  p75_minor = excluded.p75_minor, sample_size = excluded.sample_size;`,
    );
  }

  // A plan left out of the file is not deleted: a subscription may still name it. The
  // owner retires one by setting `active` to false.
  for (const plan of plans) {
    lines.push(
      `insert into plans (code, name, active, limits, prices)`,
      `values (${quote(plan.code)}, ${quote(plan.name)}, ${plan.active}, ${quote(JSON.stringify(plan.limits))}::jsonb, ${quote(JSON.stringify(plan.prices))}::jsonb)`,
      `on conflict (code) do update set name = excluded.name, active = excluded.active, limits = excluded.limits, prices = excluded.prices;`,
    );
  }
  lines.push(
    `update billing_settings set grace_days = ${graceDays === null ? 'null' : String(graceDays)};`,
  );

  lines.push('commit;', '');
  return lines.join('\n');
}
