// Generated by `pnpm db:types` from the migrations (packages/db/src/typegen.ts). Do not edit.
// Once the Supabase project exists (docs/02 B-06), `pnpm db:types:supabase` replaces it.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      affiliates: {
        Row: {
          active: boolean;
          code: string;
          commission_pct: number | null;
          created_at: string;
          id: string;
          org_id: string | null;
          owner_email: string | null;
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          code: string;
          commission_pct?: number | null;
          created_at?: string;
          id?: string;
          org_id?: string | null;
          owner_email?: string | null;
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          code?: string;
          commission_pct?: number | null;
          created_at?: string;
          id?: string;
          org_id?: string | null;
          owner_email?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'affiliates_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      attribution: {
        Row: {
          affiliate_id: string | null;
          converted_at: string | null;
          created_at: string;
          first_seen_at: string;
          id: string;
          landing_page: string | null;
          org_id: string | null;
          signed_up_at: string | null;
          source: string | null;
          updated_at: string;
        };
        Insert: {
          affiliate_id?: string | null;
          converted_at?: string | null;
          created_at?: string;
          first_seen_at?: string;
          id?: string;
          landing_page?: string | null;
          org_id?: string | null;
          signed_up_at?: string | null;
          source?: string | null;
          updated_at?: string;
        };
        Update: {
          affiliate_id?: string | null;
          converted_at?: string | null;
          created_at?: string;
          first_seen_at?: string;
          id?: string;
          landing_page?: string | null;
          org_id?: string | null;
          signed_up_at?: string | null;
          source?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'attribution_affiliate_id_fkey';
            columns: ['affiliate_id'];
            isOneToOne: false;
            referencedRelation: 'affiliates';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'attribution_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      auto_replies: {
        Row: {
          active: boolean;
          approved_by: string | null;
          body: string;
          created_at: string;
          id: string;
          name: string;
          offline_after_minutes: number;
          org_id: string;
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          approved_by?: string | null;
          body: string;
          created_at?: string;
          id?: string;
          name: string;
          offline_after_minutes?: number;
          org_id: string;
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          approved_by?: string | null;
          body?: string;
          created_at?: string;
          id?: string;
          name?: string;
          offline_after_minutes?: number;
          org_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'auto_replies_approved_by_fkey';
            columns: ['approved_by'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'auto_replies_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      auto_reply_sends: {
        Row: {
          auto_reply_id: string;
          created_at: string;
          id: string;
          message_id: string | null;
          org_id: string;
          thread_id: string;
          updated_at: string;
        };
        Insert: {
          auto_reply_id: string;
          created_at?: string;
          id?: string;
          message_id?: string | null;
          org_id: string;
          thread_id: string;
          updated_at?: string;
        };
        Update: {
          auto_reply_id?: string;
          created_at?: string;
          id?: string;
          message_id?: string | null;
          org_id?: string;
          thread_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'auto_reply_sends_auto_reply_id_fkey';
            columns: ['auto_reply_id'];
            isOneToOne: false;
            referencedRelation: 'auto_replies';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'auto_reply_sends_message_id_fkey';
            columns: ['message_id'];
            isOneToOne: false;
            referencedRelation: 'messages';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'auto_reply_sends_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'auto_reply_sends_thread_id_fkey';
            columns: ['thread_id'];
            isOneToOne: true;
            referencedRelation: 'threads';
            referencedColumns: ['id'];
          },
        ];
      };
      billing_checkouts: {
        Row: {
          created_at: string;
          created_by: string | null;
          currency: string;
          external_session_id: string | null;
          id: string;
          org_id: string;
          plan_code: string;
          provider: string;
          reference: string;
          status: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          currency: string;
          external_session_id?: string | null;
          id?: string;
          org_id: string;
          plan_code: string;
          provider: string;
          reference: string;
          status?: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          currency?: string;
          external_session_id?: string | null;
          id?: string;
          org_id?: string;
          plan_code?: string;
          provider?: string;
          reference?: string;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'billing_checkouts_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'billing_checkouts_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      billing_settings: {
        Row: {
          created_at: string;
          grace_days: number | null;
          id: string;
          singleton: boolean;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          grace_days?: number | null;
          id?: string;
          singleton?: boolean;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          grace_days?: number | null;
          id?: string;
          singleton?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      billing_webhook_receipts: {
        Row: {
          created_at: string;
          detail: string | null;
          event_key: string;
          event_type: string;
          id: string;
          org_id: string | null;
          outcome: string;
          provider: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          detail?: string | null;
          event_key: string;
          event_type: string;
          id?: string;
          org_id?: string | null;
          outcome: string;
          provider: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          detail?: string | null;
          event_key?: string;
          event_type?: string;
          id?: string;
          org_id?: string | null;
          outcome?: string;
          provider?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'billing_webhook_receipts_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      briefs: {
        Row: {
          acceptance_criteria: string[];
          assets_missing: string[];
          assets_provided: string[];
          budget_currency: string | null;
          budget_max_minor: number | null;
          budget_min_minor: number | null;
          budget_type: Database['public']['Enums']['budget_type'] | null;
          category_slug: string | null;
          created_at: string;
          deadline: string | null;
          deadline_fixed: boolean | null;
          delivery_route: Database['public']['Enums']['delivery_route'] | null;
          id: string;
          later: string[];
          locked: boolean;
          locked_at: string | null;
          must_haves: string[];
          org_id: string;
          outcome: string;
          references_: string[];
          risks: string[];
          sign_off_name: string | null;
          sign_off_response_time: string | null;
          tech_constraints: string[];
          thread_id: string;
          title: string;
          updated_at: string;
          users: string | null;
          version: number;
        };
        Insert: {
          acceptance_criteria?: string[];
          assets_missing?: string[];
          assets_provided?: string[];
          budget_currency?: string | null;
          budget_max_minor?: number | null;
          budget_min_minor?: number | null;
          budget_type?: Database['public']['Enums']['budget_type'] | null;
          category_slug?: string | null;
          created_at?: string;
          deadline?: string | null;
          deadline_fixed?: boolean | null;
          delivery_route?: Database['public']['Enums']['delivery_route'] | null;
          id?: string;
          later?: string[];
          locked?: boolean;
          locked_at?: string | null;
          must_haves?: string[];
          org_id: string;
          outcome: string;
          references_?: string[];
          risks?: string[];
          sign_off_name?: string | null;
          sign_off_response_time?: string | null;
          tech_constraints?: string[];
          thread_id: string;
          title: string;
          updated_at?: string;
          users?: string | null;
          version?: number;
        };
        Update: {
          acceptance_criteria?: string[];
          assets_missing?: string[];
          assets_provided?: string[];
          budget_currency?: string | null;
          budget_max_minor?: number | null;
          budget_min_minor?: number | null;
          budget_type?: Database['public']['Enums']['budget_type'] | null;
          category_slug?: string | null;
          created_at?: string;
          deadline?: string | null;
          deadline_fixed?: boolean | null;
          delivery_route?: Database['public']['Enums']['delivery_route'] | null;
          id?: string;
          later?: string[];
          locked?: boolean;
          locked_at?: string | null;
          must_haves?: string[];
          org_id?: string;
          outcome?: string;
          references_?: string[];
          risks?: string[];
          sign_off_name?: string | null;
          sign_off_response_time?: string | null;
          tech_constraints?: string[];
          thread_id?: string;
          title?: string;
          updated_at?: string;
          users?: string | null;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'briefs_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'briefs_thread_id_fkey';
            columns: ['thread_id'];
            isOneToOne: false;
            referencedRelation: 'threads';
            referencedColumns: ['id'];
          },
        ];
      };
      delivery_estimates: {
        Row: {
          brief_id: string | null;
          category_slug: string | null;
          created_at: string;
          currency: string;
          expected_minor: number;
          high_minor: number;
          id: string;
          job_id: string | null;
          low_minor: number;
          method: Database['public']['Enums']['estimate_method'];
          org_id: string;
          supplier_candidate_id: string | null;
          supplier_id: string | null;
          turnaround_days: number | null;
          updated_at: string;
        };
        Insert: {
          brief_id?: string | null;
          category_slug?: string | null;
          created_at?: string;
          currency: string;
          expected_minor: number;
          high_minor: number;
          id?: string;
          job_id?: string | null;
          low_minor: number;
          method: Database['public']['Enums']['estimate_method'];
          org_id: string;
          supplier_candidate_id?: string | null;
          supplier_id?: string | null;
          turnaround_days?: number | null;
          updated_at?: string;
        };
        Update: {
          brief_id?: string | null;
          category_slug?: string | null;
          created_at?: string;
          currency?: string;
          expected_minor?: number;
          high_minor?: number;
          id?: string;
          job_id?: string | null;
          low_minor?: number;
          method?: Database['public']['Enums']['estimate_method'];
          org_id?: string;
          supplier_candidate_id?: string | null;
          supplier_id?: string | null;
          turnaround_days?: number | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'delivery_estimates_brief_id_fkey';
            columns: ['brief_id'];
            isOneToOne: false;
            referencedRelation: 'briefs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'delivery_estimates_category_slug_fkey';
            columns: ['category_slug'];
            isOneToOne: false;
            referencedRelation: 'service_categories';
            referencedColumns: ['slug'];
          },
          {
            foreignKeyName: 'delivery_estimates_job_id_fkey';
            columns: ['job_id'];
            isOneToOne: false;
            referencedRelation: 'jobs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'delivery_estimates_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'delivery_estimates_supplier_candidate_id_fkey';
            columns: ['supplier_candidate_id'];
            isOneToOne: false;
            referencedRelation: 'supplier_candidates';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'delivery_estimates_supplier_id_fkey';
            columns: ['supplier_id'];
            isOneToOne: false;
            referencedRelation: 'suppliers';
            referencedColumns: ['id'];
          },
        ];
      };
      delivery_orders: {
        Row: {
          accepted_at: string | null;
          agreed_cost_minor: number | null;
          brief_id: string | null;
          cancelled_at: string | null;
          created_at: string;
          currency: string | null;
          delivered_at: string | null;
          due_at: string | null;
          handed_over_at: string | null;
          handover: Json;
          id: string;
          milestones: Json;
          org_id: string;
          pipeline_item_id: string;
          sourcing_request_id: string | null;
          status: Database['public']['Enums']['delivery_order_status'];
          supplier_candidate_id: string | null;
          supplier_id: string | null;
          updated_at: string;
        };
        Insert: {
          accepted_at?: string | null;
          agreed_cost_minor?: number | null;
          brief_id?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          currency?: string | null;
          delivered_at?: string | null;
          due_at?: string | null;
          handed_over_at?: string | null;
          handover?: Json;
          id?: string;
          milestones?: Json;
          org_id: string;
          pipeline_item_id: string;
          sourcing_request_id?: string | null;
          status?: Database['public']['Enums']['delivery_order_status'];
          supplier_candidate_id?: string | null;
          supplier_id?: string | null;
          updated_at?: string;
        };
        Update: {
          accepted_at?: string | null;
          agreed_cost_minor?: number | null;
          brief_id?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          currency?: string | null;
          delivered_at?: string | null;
          due_at?: string | null;
          handed_over_at?: string | null;
          handover?: Json;
          id?: string;
          milestones?: Json;
          org_id?: string;
          pipeline_item_id?: string;
          sourcing_request_id?: string | null;
          status?: Database['public']['Enums']['delivery_order_status'];
          supplier_candidate_id?: string | null;
          supplier_id?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'delivery_orders_brief_id_fkey';
            columns: ['brief_id'];
            isOneToOne: false;
            referencedRelation: 'briefs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'delivery_orders_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'delivery_orders_pipeline_item_id_fkey';
            columns: ['pipeline_item_id'];
            isOneToOne: true;
            referencedRelation: 'pipeline_items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'delivery_orders_sourcing_request_id_fkey';
            columns: ['sourcing_request_id'];
            isOneToOne: false;
            referencedRelation: 'sourcing_requests';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'delivery_orders_supplier_candidate_id_fkey';
            columns: ['supplier_candidate_id'];
            isOneToOne: false;
            referencedRelation: 'supplier_candidates';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'delivery_orders_supplier_id_fkey';
            columns: ['supplier_id'];
            isOneToOne: false;
            referencedRelation: 'suppliers';
            referencedColumns: ['id'];
          },
        ];
      };
      discovery_sessions: {
        Row: {
          answers: Json;
          asked: Json;
          completeness: number;
          created_at: string;
          id: string;
          org_id: string;
          question_set_version: string;
          redacted_at: string | null;
          thread_id: string;
          updated_at: string;
        };
        Insert: {
          answers?: Json;
          asked?: Json;
          completeness?: number;
          created_at?: string;
          id?: string;
          org_id: string;
          question_set_version: string;
          redacted_at?: string | null;
          thread_id: string;
          updated_at?: string;
        };
        Update: {
          answers?: Json;
          asked?: Json;
          completeness?: number;
          created_at?: string;
          id?: string;
          org_id?: string;
          question_set_version?: string;
          redacted_at?: string | null;
          thread_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'discovery_sessions_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'discovery_sessions_thread_id_fkey';
            columns: ['thread_id'];
            isOneToOne: false;
            referencedRelation: 'threads';
            referencedColumns: ['id'];
          },
        ];
      };
      events: {
        Row: {
          actor_kind: string;
          actor_user_id: string | null;
          created_at: string;
          id: string;
          org_id: string | null;
          outcome: string | null;
          payload: Json;
          request_id: string | null;
          subject_id: string | null;
          subject_table: string | null;
          type: string;
        };
        Insert: {
          actor_kind?: string;
          actor_user_id?: string | null;
          created_at?: string;
          id?: string;
          org_id?: string | null;
          outcome?: string | null;
          payload?: Json;
          request_id?: string | null;
          subject_id?: string | null;
          subject_table?: string | null;
          type: string;
        };
        Update: {
          actor_kind?: string;
          actor_user_id?: string | null;
          created_at?: string;
          id?: string;
          org_id?: string | null;
          outcome?: string | null;
          payload?: Json;
          request_id?: string | null;
          subject_id?: string | null;
          subject_table?: string | null;
          type?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'events_actor_user_id_fkey';
            columns: ['actor_user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'events_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      job_scores: {
        Row: {
          cost_usd_minor: number | null;
          created_at: string;
          flags: string[];
          id: string;
          input_tokens: number | null;
          job_id: string;
          model: string;
          org_id: string;
          output_tokens: number | null;
          reasons: string[];
          reply_probability: number | null;
          score: number;
          updated_at: string;
          verdict: Database['public']['Enums']['score_verdict'];
        };
        Insert: {
          cost_usd_minor?: number | null;
          created_at?: string;
          flags?: string[];
          id?: string;
          input_tokens?: number | null;
          job_id: string;
          model: string;
          org_id: string;
          output_tokens?: number | null;
          reasons?: string[];
          reply_probability?: number | null;
          score: number;
          updated_at?: string;
          verdict: Database['public']['Enums']['score_verdict'];
        };
        Update: {
          cost_usd_minor?: number | null;
          created_at?: string;
          flags?: string[];
          id?: string;
          input_tokens?: number | null;
          job_id?: string;
          model?: string;
          org_id?: string;
          output_tokens?: number | null;
          reasons?: string[];
          reply_probability?: number | null;
          score?: number;
          updated_at?: string;
          verdict?: Database['public']['Enums']['score_verdict'];
        };
        Relationships: [
          {
            foreignKeyName: 'job_scores_job_id_fkey';
            columns: ['job_id'];
            isOneToOne: false;
            referencedRelation: 'jobs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'job_scores_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      jobs: {
        Row: {
          average_bid_minor: number | null;
          bid_count: number | null;
          budget_max_minor: number | null;
          budget_min_minor: number | null;
          category_confidence: number | null;
          category_slug: string | null;
          client_country: string | null;
          client_payment_verified: boolean | null;
          client_rating: number | null;
          client_spend_minor: number | null;
          created_at: string;
          currency: string | null;
          description: string | null;
          external_id: string;
          fetched_at: string;
          first_seen_at: string;
          hourly: boolean;
          id: string;
          org_id: string;
          platform: Database['public']['Enums']['platform'];
          posted_at: string | null;
          raw: Json;
          scanner_id: string | null;
          skills: string[];
          title: string;
          updated_at: string;
        };
        Insert: {
          average_bid_minor?: number | null;
          bid_count?: number | null;
          budget_max_minor?: number | null;
          budget_min_minor?: number | null;
          category_confidence?: number | null;
          category_slug?: string | null;
          client_country?: string | null;
          client_payment_verified?: boolean | null;
          client_rating?: number | null;
          client_spend_minor?: number | null;
          created_at?: string;
          currency?: string | null;
          description?: string | null;
          external_id: string;
          fetched_at?: string;
          first_seen_at?: string;
          hourly?: boolean;
          id?: string;
          org_id: string;
          platform: Database['public']['Enums']['platform'];
          posted_at?: string | null;
          raw: Json;
          scanner_id?: string | null;
          skills?: string[];
          title: string;
          updated_at?: string;
        };
        Update: {
          average_bid_minor?: number | null;
          bid_count?: number | null;
          budget_max_minor?: number | null;
          budget_min_minor?: number | null;
          category_confidence?: number | null;
          category_slug?: string | null;
          client_country?: string | null;
          client_payment_verified?: boolean | null;
          client_rating?: number | null;
          client_spend_minor?: number | null;
          created_at?: string;
          currency?: string | null;
          description?: string | null;
          external_id?: string;
          fetched_at?: string;
          first_seen_at?: string;
          hourly?: boolean;
          id?: string;
          org_id?: string;
          platform?: Database['public']['Enums']['platform'];
          posted_at?: string | null;
          raw?: Json;
          scanner_id?: string | null;
          skills?: string[];
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'jobs_category_slug_fkey';
            columns: ['category_slug'];
            isOneToOne: false;
            referencedRelation: 'service_categories';
            referencedColumns: ['slug'];
          },
          {
            foreignKeyName: 'jobs_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'jobs_scanner_id_fkey';
            columns: ['scanner_id'];
            isOneToOne: false;
            referencedRelation: 'scanners';
            referencedColumns: ['id'];
          },
        ];
      };
      llm_calls: {
        Row: {
          attempts: number;
          cache_read_tokens: number;
          cache_write_tokens: number;
          cost_nano_usd: number;
          created_at: string;
          id: string;
          input_tokens: number;
          model: string;
          org_id: string;
          outcome: Database['public']['Enums']['llm_outcome'];
          output_tokens: number;
          problems: Json;
          purpose: Database['public']['Enums']['llm_purpose'];
          request_id: string | null;
          subject_id: string | null;
          subject_table: string | null;
          updated_at: string;
        };
        Insert: {
          attempts?: number;
          cache_read_tokens?: number;
          cache_write_tokens?: number;
          cost_nano_usd?: number;
          created_at?: string;
          id?: string;
          input_tokens?: number;
          model: string;
          org_id: string;
          outcome?: Database['public']['Enums']['llm_outcome'];
          output_tokens?: number;
          problems?: Json;
          purpose: Database['public']['Enums']['llm_purpose'];
          request_id?: string | null;
          subject_id?: string | null;
          subject_table?: string | null;
          updated_at?: string;
        };
        Update: {
          attempts?: number;
          cache_read_tokens?: number;
          cache_write_tokens?: number;
          cost_nano_usd?: number;
          created_at?: string;
          id?: string;
          input_tokens?: number;
          model?: string;
          org_id?: string;
          outcome?: Database['public']['Enums']['llm_outcome'];
          output_tokens?: number;
          problems?: Json;
          purpose?: Database['public']['Enums']['llm_purpose'];
          request_id?: string | null;
          subject_id?: string | null;
          subject_table?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'llm_calls_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      margin_evaluations: {
        Row: {
          brief_id: string | null;
          client_budget_minor: number;
          created_at: string;
          currency: string;
          delivery_estimate_id: string | null;
          fx_buffer_minor: number;
          fx_rate_at: string | null;
          fx_rate_used: number | null;
          id: string;
          job_id: string | null;
          margin_minor: number;
          margin_pct: number;
          min_margin_pct: number;
          min_margin_zar_minor: number;
          org_id: string;
          passed: boolean;
          platform_fee_minor: number;
          reason: string | null;
          supplier_cost_minor: number;
          tool_cost_minor: number;
          updated_at: string;
        };
        Insert: {
          brief_id?: string | null;
          client_budget_minor: number;
          created_at?: string;
          currency: string;
          delivery_estimate_id?: string | null;
          fx_buffer_minor: number;
          fx_rate_at?: string | null;
          fx_rate_used?: number | null;
          id?: string;
          job_id?: string | null;
          margin_minor: number;
          margin_pct: number;
          min_margin_pct: number;
          min_margin_zar_minor: number;
          org_id: string;
          passed: boolean;
          platform_fee_minor: number;
          reason?: string | null;
          supplier_cost_minor: number;
          tool_cost_minor?: number;
          updated_at?: string;
        };
        Update: {
          brief_id?: string | null;
          client_budget_minor?: number;
          created_at?: string;
          currency?: string;
          delivery_estimate_id?: string | null;
          fx_buffer_minor?: number;
          fx_rate_at?: string | null;
          fx_rate_used?: number | null;
          id?: string;
          job_id?: string | null;
          margin_minor?: number;
          margin_pct?: number;
          min_margin_pct?: number;
          min_margin_zar_minor?: number;
          org_id?: string;
          passed?: boolean;
          platform_fee_minor?: number;
          reason?: string | null;
          supplier_cost_minor?: number;
          tool_cost_minor?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'margin_evaluations_brief_id_fkey';
            columns: ['brief_id'];
            isOneToOne: false;
            referencedRelation: 'briefs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'margin_evaluations_delivery_estimate_id_fkey';
            columns: ['delivery_estimate_id'];
            isOneToOne: false;
            referencedRelation: 'delivery_estimates';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'margin_evaluations_job_id_fkey';
            columns: ['job_id'];
            isOneToOne: false;
            referencedRelation: 'jobs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'margin_evaluations_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      market_price_bands: {
        Row: {
          category_slug: string;
          created_at: string;
          currency: string;
          id: string;
          p25_minor: number;
          p50_minor: number;
          p75_minor: number;
          sample_size: number;
          sampled_at: string;
          source: Database['public']['Enums']['price_band_source'];
          updated_at: string;
        };
        Insert: {
          category_slug: string;
          created_at?: string;
          currency: string;
          id?: string;
          p25_minor: number;
          p50_minor: number;
          p75_minor: number;
          sample_size?: number;
          sampled_at?: string;
          source: Database['public']['Enums']['price_band_source'];
          updated_at?: string;
        };
        Update: {
          category_slug?: string;
          created_at?: string;
          currency?: string;
          id?: string;
          p25_minor?: number;
          p50_minor?: number;
          p75_minor?: number;
          sample_size?: number;
          sampled_at?: string;
          source?: Database['public']['Enums']['price_band_source'];
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'market_price_bands_category_slug_fkey';
            columns: ['category_slug'];
            isOneToOne: false;
            referencedRelation: 'service_categories';
            referencedColumns: ['slug'];
          },
        ];
      };
      memberships: {
        Row: {
          created_at: string;
          id: string;
          org_id: string;
          role: Database['public']['Enums']['user_role'];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          org_id: string;
          role?: Database['public']['Enums']['user_role'];
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          org_id?: string;
          role?: Database['public']['Enums']['user_role'];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'memberships_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'memberships_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      messages: {
        Row: {
          approved_by: string | null;
          approved_via: Database['public']['Enums']['approval_channel'] | null;
          body: string;
          created_at: string;
          direction: Database['public']['Enums']['message_direction'];
          external_message_id: string | null;
          failure_reason: string | null;
          id: string;
          org_id: string;
          origin: string;
          redacted_at: string | null;
          rejected_at: string | null;
          sent_at: string | null;
          thread_id: string;
          updated_at: string;
        };
        Insert: {
          approved_by?: string | null;
          approved_via?: Database['public']['Enums']['approval_channel'] | null;
          body: string;
          created_at?: string;
          direction: Database['public']['Enums']['message_direction'];
          external_message_id?: string | null;
          failure_reason?: string | null;
          id?: string;
          org_id: string;
          origin?: string;
          redacted_at?: string | null;
          rejected_at?: string | null;
          sent_at?: string | null;
          thread_id: string;
          updated_at?: string;
        };
        Update: {
          approved_by?: string | null;
          approved_via?: Database['public']['Enums']['approval_channel'] | null;
          body?: string;
          created_at?: string;
          direction?: Database['public']['Enums']['message_direction'];
          external_message_id?: string | null;
          failure_reason?: string | null;
          id?: string;
          org_id?: string;
          origin?: string;
          redacted_at?: string | null;
          rejected_at?: string | null;
          sent_at?: string | null;
          thread_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'messages_approved_by_fkey';
            columns: ['approved_by'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'messages_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'messages_thread_id_fkey';
            columns: ['thread_id'];
            isOneToOne: false;
            referencedRelation: 'threads';
            referencedColumns: ['id'];
          },
        ];
      };
      orgs: {
        Row: {
          base_currency: string;
          billing_exempt: boolean;
          country_code: string;
          created_at: string;
          id: string;
          name: string;
          updated_at: string;
        };
        Insert: {
          base_currency?: string;
          billing_exempt?: boolean;
          country_code?: string;
          created_at?: string;
          id?: string;
          name: string;
          updated_at?: string;
        };
        Update: {
          base_currency?: string;
          billing_exempt?: boolean;
          country_code?: string;
          created_at?: string;
          id?: string;
          name?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          amount_minor: number;
          amount_zar_minor: number | null;
          created_at: string;
          currency: string;
          delivery_order_id: string | null;
          direction: Database['public']['Enums']['payment_direction'];
          fx_rate_at: string | null;
          fx_rate_used: number | null;
          id: string;
          kind: Database['public']['Enums']['payment_kind'];
          milestone_index: number | null;
          note: string | null;
          org_id: string;
          paid_at: string | null;
          pipeline_item_id: string | null;
          recorded_by: string | null;
          reference: string | null;
          updated_at: string;
        };
        Insert: {
          amount_minor: number;
          amount_zar_minor?: number | null;
          created_at?: string;
          currency: string;
          delivery_order_id?: string | null;
          direction: Database['public']['Enums']['payment_direction'];
          fx_rate_at?: string | null;
          fx_rate_used?: number | null;
          id?: string;
          kind: Database['public']['Enums']['payment_kind'];
          milestone_index?: number | null;
          note?: string | null;
          org_id: string;
          paid_at?: string | null;
          pipeline_item_id?: string | null;
          recorded_by?: string | null;
          reference?: string | null;
          updated_at?: string;
        };
        Update: {
          amount_minor?: number;
          amount_zar_minor?: number | null;
          created_at?: string;
          currency?: string;
          delivery_order_id?: string | null;
          direction?: Database['public']['Enums']['payment_direction'];
          fx_rate_at?: string | null;
          fx_rate_used?: number | null;
          id?: string;
          kind?: Database['public']['Enums']['payment_kind'];
          milestone_index?: number | null;
          note?: string | null;
          org_id?: string;
          paid_at?: string | null;
          pipeline_item_id?: string | null;
          recorded_by?: string | null;
          reference?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'payments_delivery_order_id_fkey';
            columns: ['delivery_order_id'];
            isOneToOne: false;
            referencedRelation: 'delivery_orders';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'payments_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'payments_pipeline_item_id_fkey';
            columns: ['pipeline_item_id'];
            isOneToOne: false;
            referencedRelation: 'pipeline_items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'payments_recorded_by_fkey';
            columns: ['recorded_by'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      pipeline_items: {
        Row: {
          created_at: string;
          currency: string | null;
          id: string;
          job_id: string;
          org_id: string;
          proposal_id: string | null;
          retainer: boolean;
          retainer_monthly_minor: number | null;
          stage: Database['public']['Enums']['pipeline_stage'];
          stage_changed_at: string;
          thread_id: string | null;
          updated_at: string;
          value_minor: number | null;
        };
        Insert: {
          created_at?: string;
          currency?: string | null;
          id?: string;
          job_id: string;
          org_id: string;
          proposal_id?: string | null;
          retainer?: boolean;
          retainer_monthly_minor?: number | null;
          stage?: Database['public']['Enums']['pipeline_stage'];
          stage_changed_at?: string;
          thread_id?: string | null;
          updated_at?: string;
          value_minor?: number | null;
        };
        Update: {
          created_at?: string;
          currency?: string | null;
          id?: string;
          job_id?: string;
          org_id?: string;
          proposal_id?: string | null;
          retainer?: boolean;
          retainer_monthly_minor?: number | null;
          stage?: Database['public']['Enums']['pipeline_stage'];
          stage_changed_at?: string;
          thread_id?: string | null;
          updated_at?: string;
          value_minor?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: 'pipeline_items_job_id_fkey';
            columns: ['job_id'];
            isOneToOne: true;
            referencedRelation: 'jobs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pipeline_items_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pipeline_items_proposal_id_fkey';
            columns: ['proposal_id'];
            isOneToOne: false;
            referencedRelation: 'proposals';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pipeline_items_thread_id_fkey';
            columns: ['thread_id'];
            isOneToOne: false;
            referencedRelation: 'threads';
            referencedColumns: ['id'];
          },
        ];
      };
      plans: {
        Row: {
          active: boolean;
          code: string;
          created_at: string;
          id: string;
          limits: Json;
          name: string;
          prices: Json;
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          code: string;
          created_at?: string;
          id?: string;
          limits: Json;
          name: string;
          prices?: Json;
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          code?: string;
          created_at?: string;
          id?: string;
          limits?: Json;
          name?: string;
          prices?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      platform_accounts: {
        Row: {
          access_token_secret_id: string | null;
          created_at: string;
          external_user_id: string;
          external_username: string | null;
          id: string;
          inbox_synced_to: string | null;
          last_sync_at: string | null;
          monthly_bid_allowance: number | null;
          org_id: string;
          plan_name: string | null;
          plan_recorded_on: string | null;
          platform: Database['public']['Enums']['platform'];
          refresh_token_secret_id: string | null;
          scopes: string[];
          status: Database['public']['Enums']['platform_account_status'];
          token_expires_at: string | null;
          updated_at: string;
        };
        Insert: {
          access_token_secret_id?: string | null;
          created_at?: string;
          external_user_id: string;
          external_username?: string | null;
          id?: string;
          inbox_synced_to?: string | null;
          last_sync_at?: string | null;
          monthly_bid_allowance?: number | null;
          org_id: string;
          plan_name?: string | null;
          plan_recorded_on?: string | null;
          platform: Database['public']['Enums']['platform'];
          refresh_token_secret_id?: string | null;
          scopes?: string[];
          status?: Database['public']['Enums']['platform_account_status'];
          token_expires_at?: string | null;
          updated_at?: string;
        };
        Update: {
          access_token_secret_id?: string | null;
          created_at?: string;
          external_user_id?: string;
          external_username?: string | null;
          id?: string;
          inbox_synced_to?: string | null;
          last_sync_at?: string | null;
          monthly_bid_allowance?: number | null;
          org_id?: string;
          plan_name?: string | null;
          plan_recorded_on?: string | null;
          platform?: Database['public']['Enums']['platform'];
          refresh_token_secret_id?: string | null;
          scopes?: string[];
          status?: Database['public']['Enums']['platform_account_status'];
          token_expires_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'platform_accounts_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      platform_connect_attempts: {
        Row: {
          created_at: string;
          expires_at: string;
          id: string;
          org_id: string;
          platform: Database['public']['Enums']['platform'];
          updated_at: string;
          used_at: string | null;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          expires_at: string;
          id?: string;
          org_id: string;
          platform: Database['public']['Enums']['platform'];
          updated_at?: string;
          used_at?: string | null;
          user_id: string;
        };
        Update: {
          created_at?: string;
          expires_at?: string;
          id?: string;
          org_id?: string;
          platform?: Database['public']['Enums']['platform'];
          updated_at?: string;
          used_at?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'platform_connect_attempts_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'platform_connect_attempts_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      portfolio_items: {
        Row: {
          active: boolean;
          category_slug: string | null;
          created_at: string;
          description: string | null;
          id: string;
          kind: Database['public']['Enums']['portfolio_kind'];
          org_id: string;
          permission_to_show: boolean;
          title: string;
          updated_at: string;
          url: string | null;
        };
        Insert: {
          active?: boolean;
          category_slug?: string | null;
          created_at?: string;
          description?: string | null;
          id?: string;
          kind: Database['public']['Enums']['portfolio_kind'];
          org_id: string;
          permission_to_show?: boolean;
          title: string;
          updated_at?: string;
          url?: string | null;
        };
        Update: {
          active?: boolean;
          category_slug?: string | null;
          created_at?: string;
          description?: string | null;
          id?: string;
          kind?: Database['public']['Enums']['portfolio_kind'];
          org_id?: string;
          permission_to_show?: boolean;
          title?: string;
          updated_at?: string;
          url?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'portfolio_items_category_slug_fkey';
            columns: ['category_slug'];
            isOneToOne: false;
            referencedRelation: 'service_categories';
            referencedColumns: ['slug'];
          },
          {
            foreignKeyName: 'portfolio_items_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      proposal_citations: {
        Row: {
          created_at: string;
          id: string;
          org_id: string;
          portfolio_item_id: string;
          proposal_id: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          org_id: string;
          portfolio_item_id: string;
          proposal_id: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          org_id?: string;
          portfolio_item_id?: string;
          proposal_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'proposal_citations_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'proposal_citations_portfolio_item_id_fkey';
            columns: ['portfolio_item_id'];
            isOneToOne: false;
            referencedRelation: 'portfolio_items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'proposal_citations_proposal_id_fkey';
            columns: ['proposal_id'];
            isOneToOne: false;
            referencedRelation: 'proposals';
            referencedColumns: ['id'];
          },
        ];
      };
      proposals: {
        Row: {
          amount_minor: number;
          approved_by: string | null;
          approved_via: Database['public']['Enums']['approval_channel'] | null;
          body: string;
          created_at: string;
          currency: string;
          delivery_days: number;
          failure_reason: string | null;
          id: string;
          job_id: string;
          margin_evaluation_id: string | null;
          milestones: Json;
          org_id: string;
          platform_ref: string | null;
          status: Database['public']['Enums']['proposal_status'];
          submitted_at: string | null;
          template_variant_id: string | null;
          updated_at: string;
        };
        Insert: {
          amount_minor: number;
          approved_by?: string | null;
          approved_via?: Database['public']['Enums']['approval_channel'] | null;
          body: string;
          created_at?: string;
          currency: string;
          delivery_days: number;
          failure_reason?: string | null;
          id?: string;
          job_id: string;
          margin_evaluation_id?: string | null;
          milestones?: Json;
          org_id: string;
          platform_ref?: string | null;
          status?: Database['public']['Enums']['proposal_status'];
          submitted_at?: string | null;
          template_variant_id?: string | null;
          updated_at?: string;
        };
        Update: {
          amount_minor?: number;
          approved_by?: string | null;
          approved_via?: Database['public']['Enums']['approval_channel'] | null;
          body?: string;
          created_at?: string;
          currency?: string;
          delivery_days?: number;
          failure_reason?: string | null;
          id?: string;
          job_id?: string;
          margin_evaluation_id?: string | null;
          milestones?: Json;
          org_id?: string;
          platform_ref?: string | null;
          status?: Database['public']['Enums']['proposal_status'];
          submitted_at?: string | null;
          template_variant_id?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'proposals_approved_by_fkey';
            columns: ['approved_by'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'proposals_job_id_fkey';
            columns: ['job_id'];
            isOneToOne: false;
            referencedRelation: 'jobs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'proposals_margin_evaluation_id_fkey';
            columns: ['margin_evaluation_id'];
            isOneToOne: false;
            referencedRelation: 'margin_evaluations';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'proposals_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'proposals_template_variant_fk';
            columns: ['template_variant_id'];
            isOneToOne: false;
            referencedRelation: 'template_variants';
            referencedColumns: ['id'];
          },
        ];
      };
      scanners: {
        Row: {
          active: boolean;
          auto_send: boolean;
          created_at: string;
          daily_cap: number;
          filters: Json;
          id: string;
          min_score: number | null;
          name: string;
          org_id: string;
          platform: Database['public']['Enums']['platform'];
          poll_interval_seconds: number;
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          auto_send?: boolean;
          created_at?: string;
          daily_cap?: number;
          filters?: Json;
          id?: string;
          min_score?: number | null;
          name: string;
          org_id: string;
          platform?: Database['public']['Enums']['platform'];
          poll_interval_seconds?: number;
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          auto_send?: boolean;
          created_at?: string;
          daily_cap?: number;
          filters?: Json;
          id?: string;
          min_score?: number | null;
          name?: string;
          org_id?: string;
          platform?: Database['public']['Enums']['platform'];
          poll_interval_seconds?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'scanners_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      service_categories: {
        Row: {
          created_at: string;
          id: string;
          in_house: boolean;
          name: string;
          slug: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          in_house?: boolean;
          name: string;
          slug: string;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          in_house?: boolean;
          name?: string;
          slug?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      settings: {
        Row: {
          bidding_paused: boolean;
          created_at: string;
          fee_table: Json;
          fx_buffer_pct: number | null;
          id: string;
          live_mode: boolean;
          min_margin_pct: number | null;
          min_margin_zar_minor: number | null;
          org_id: string;
          retention_days: number | null;
          updated_at: string;
          vat_pct: number;
        };
        Insert: {
          bidding_paused?: boolean;
          created_at?: string;
          fee_table?: Json;
          fx_buffer_pct?: number | null;
          id?: string;
          live_mode?: boolean;
          min_margin_pct?: number | null;
          min_margin_zar_minor?: number | null;
          org_id: string;
          retention_days?: number | null;
          updated_at?: string;
          vat_pct?: number;
        };
        Update: {
          bidding_paused?: boolean;
          created_at?: string;
          fee_table?: Json;
          fx_buffer_pct?: number | null;
          id?: string;
          live_mode?: boolean;
          min_margin_pct?: number | null;
          min_margin_zar_minor?: number | null;
          org_id?: string;
          retention_days?: number | null;
          updated_at?: string;
          vat_pct?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'settings_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: true;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      sourcing_posts: {
        Row: {
          approved_by: string | null;
          approved_via: Database['public']['Enums']['approval_channel'] | null;
          body: string;
          budget_max_minor: number | null;
          budget_min_minor: number | null;
          created_at: string;
          currency: string | null;
          external_id: string | null;
          failure_reason: string | null;
          id: string;
          org_id: string;
          platform: Database['public']['Enums']['platform'];
          posted_at: string | null;
          sourcing_request_id: string;
          status: Database['public']['Enums']['sourcing_post_status'];
          title: string;
          updated_at: string;
        };
        Insert: {
          approved_by?: string | null;
          approved_via?: Database['public']['Enums']['approval_channel'] | null;
          body: string;
          budget_max_minor?: number | null;
          budget_min_minor?: number | null;
          created_at?: string;
          currency?: string | null;
          external_id?: string | null;
          failure_reason?: string | null;
          id?: string;
          org_id: string;
          platform: Database['public']['Enums']['platform'];
          posted_at?: string | null;
          sourcing_request_id: string;
          status?: Database['public']['Enums']['sourcing_post_status'];
          title?: string;
          updated_at?: string;
        };
        Update: {
          approved_by?: string | null;
          approved_via?: Database['public']['Enums']['approval_channel'] | null;
          body?: string;
          budget_max_minor?: number | null;
          budget_min_minor?: number | null;
          created_at?: string;
          currency?: string | null;
          external_id?: string | null;
          failure_reason?: string | null;
          id?: string;
          org_id?: string;
          platform?: Database['public']['Enums']['platform'];
          posted_at?: string | null;
          sourcing_request_id?: string;
          status?: Database['public']['Enums']['sourcing_post_status'];
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'sourcing_posts_approved_by_fkey';
            columns: ['approved_by'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'sourcing_posts_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'sourcing_posts_sourcing_request_id_fkey';
            columns: ['sourcing_request_id'];
            isOneToOne: false;
            referencedRelation: 'sourcing_requests';
            referencedColumns: ['id'];
          },
        ];
      };
      sourcing_requests: {
        Row: {
          brief_id: string;
          channels: Database['public']['Enums']['supplier_channel'][];
          created_at: string;
          excluded: Json;
          id: string;
          org_id: string;
          status: Database['public']['Enums']['sourcing_status'];
          updated_at: string;
        };
        Insert: {
          brief_id: string;
          channels?: Database['public']['Enums']['supplier_channel'][];
          created_at?: string;
          excluded?: Json;
          id?: string;
          org_id: string;
          status?: Database['public']['Enums']['sourcing_status'];
          updated_at?: string;
        };
        Update: {
          brief_id?: string;
          channels?: Database['public']['Enums']['supplier_channel'][];
          created_at?: string;
          excluded?: Json;
          id?: string;
          org_id?: string;
          status?: Database['public']['Enums']['sourcing_status'];
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'sourcing_requests_brief_id_fkey';
            columns: ['brief_id'];
            isOneToOne: false;
            referencedRelation: 'briefs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'sourcing_requests_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      subscriptions: {
        Row: {
          created_at: string;
          currency: string | null;
          current_period_end: string | null;
          external_customer: string | null;
          external_ref: string | null;
          grace_until: string | null;
          id: string;
          org_id: string;
          plan: string;
          provider: string | null;
          status: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          currency?: string | null;
          current_period_end?: string | null;
          external_customer?: string | null;
          external_ref?: string | null;
          grace_until?: string | null;
          id?: string;
          org_id: string;
          plan: string;
          provider?: string | null;
          status?: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          currency?: string | null;
          current_period_end?: string | null;
          external_customer?: string | null;
          external_ref?: string | null;
          grace_until?: string | null;
          id?: string;
          org_id?: string;
          plan?: string;
          provider?: string | null;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'subscriptions_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: true;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      supplier_candidates: {
        Row: {
          country_code: string | null;
          created_at: string;
          currency: string | null;
          display_name: string;
          external_bid_id: string | null;
          external_profile_url: string | null;
          id: string;
          org_id: string;
          quoted_price_minor: number | null;
          ranking: Json;
          score: number | null;
          shortlisted: boolean;
          sourcing_post_id: string | null;
          sourcing_request_id: string;
          supplier_id: string | null;
          turnaround_days: number | null;
          updated_at: string;
        };
        Insert: {
          country_code?: string | null;
          created_at?: string;
          currency?: string | null;
          display_name: string;
          external_bid_id?: string | null;
          external_profile_url?: string | null;
          id?: string;
          org_id: string;
          quoted_price_minor?: number | null;
          ranking?: Json;
          score?: number | null;
          shortlisted?: boolean;
          sourcing_post_id?: string | null;
          sourcing_request_id: string;
          supplier_id?: string | null;
          turnaround_days?: number | null;
          updated_at?: string;
        };
        Update: {
          country_code?: string | null;
          created_at?: string;
          currency?: string | null;
          display_name?: string;
          external_bid_id?: string | null;
          external_profile_url?: string | null;
          id?: string;
          org_id?: string;
          quoted_price_minor?: number | null;
          ranking?: Json;
          score?: number | null;
          shortlisted?: boolean;
          sourcing_post_id?: string | null;
          sourcing_request_id?: string;
          supplier_id?: string | null;
          turnaround_days?: number | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'supplier_candidates_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'supplier_candidates_sourcing_post_id_fkey';
            columns: ['sourcing_post_id'];
            isOneToOne: false;
            referencedRelation: 'sourcing_posts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'supplier_candidates_sourcing_request_id_fkey';
            columns: ['sourcing_request_id'];
            isOneToOne: false;
            referencedRelation: 'sourcing_requests';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'supplier_candidates_supplier_id_fkey';
            columns: ['supplier_id'];
            isOneToOne: false;
            referencedRelation: 'suppliers';
            referencedColumns: ['id'];
          },
        ];
      };
      supplier_rate_cards: {
        Row: {
          category_slug: string;
          created_at: string;
          currency: string;
          fixed_price_minor: number | null;
          hourly_rate_minor: number | null;
          id: string;
          org_id: string;
          supplier_id: string;
          turnaround_days: number | null;
          updated_at: string;
        };
        Insert: {
          category_slug: string;
          created_at?: string;
          currency: string;
          fixed_price_minor?: number | null;
          hourly_rate_minor?: number | null;
          id?: string;
          org_id: string;
          supplier_id: string;
          turnaround_days?: number | null;
          updated_at?: string;
        };
        Update: {
          category_slug?: string;
          created_at?: string;
          currency?: string;
          fixed_price_minor?: number | null;
          hourly_rate_minor?: number | null;
          id?: string;
          org_id?: string;
          supplier_id?: string;
          turnaround_days?: number | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'supplier_rate_cards_category_slug_fkey';
            columns: ['category_slug'];
            isOneToOne: false;
            referencedRelation: 'service_categories';
            referencedColumns: ['slug'];
          },
          {
            foreignKeyName: 'supplier_rate_cards_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'supplier_rate_cards_supplier_id_fkey';
            columns: ['supplier_id'];
            isOneToOne: false;
            referencedRelation: 'suppliers';
            referencedColumns: ['id'];
          },
        ];
      };
      suppliers: {
        Row: {
          active: boolean;
          channel: Database['public']['Enums']['supplier_channel'];
          country_code: string | null;
          created_at: string;
          external_profile_url: string | null;
          id: string;
          languages: string[];
          name: string;
          notes: string | null;
          on_time_rate: number | null;
          org_id: string;
          pays_after_delivery: boolean;
          quality_score: number | null;
          time_zone: string | null;
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          channel: Database['public']['Enums']['supplier_channel'];
          country_code?: string | null;
          created_at?: string;
          external_profile_url?: string | null;
          id?: string;
          languages?: string[];
          name: string;
          notes?: string | null;
          on_time_rate?: number | null;
          org_id: string;
          pays_after_delivery?: boolean;
          quality_score?: number | null;
          time_zone?: string | null;
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          channel?: Database['public']['Enums']['supplier_channel'];
          country_code?: string | null;
          created_at?: string;
          external_profile_url?: string | null;
          id?: string;
          languages?: string[];
          name?: string;
          notes?: string | null;
          on_time_rate?: number | null;
          org_id?: string;
          pays_after_delivery?: boolean;
          quality_score?: number | null;
          time_zone?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'suppliers_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      telegram_link_codes: {
        Row: {
          code: string;
          created_at: string;
          expires_at: string;
          id: string;
          org_id: string;
          updated_at: string;
          used_at: string | null;
          user_id: string;
        };
        Insert: {
          code: string;
          created_at?: string;
          expires_at: string;
          id?: string;
          org_id: string;
          updated_at?: string;
          used_at?: string | null;
          user_id: string;
        };
        Update: {
          code?: string;
          created_at?: string;
          expires_at?: string;
          id?: string;
          org_id?: string;
          updated_at?: string;
          used_at?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'telegram_link_codes_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'telegram_link_codes_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      telegram_pending: {
        Row: {
          action: string;
          chat_id: string;
          created_at: string;
          id: string;
          org_id: string;
          proposal_id: string;
          updated_at: string;
        };
        Insert: {
          action: string;
          chat_id: string;
          created_at?: string;
          id?: string;
          org_id: string;
          proposal_id: string;
          updated_at?: string;
        };
        Update: {
          action?: string;
          chat_id?: string;
          created_at?: string;
          id?: string;
          org_id?: string;
          proposal_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'telegram_pending_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'telegram_pending_proposal_id_fkey';
            columns: ['proposal_id'];
            isOneToOne: false;
            referencedRelation: 'proposals';
            referencedColumns: ['id'];
          },
        ];
      };
      template_variants: {
        Row: {
          active: boolean;
          body: string;
          created_at: string;
          id: string;
          label: string;
          org_id: string;
          template_id: string;
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          body: string;
          created_at?: string;
          id?: string;
          label: string;
          org_id: string;
          template_id: string;
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          body?: string;
          created_at?: string;
          id?: string;
          label?: string;
          org_id?: string;
          template_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'template_variants_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'template_variants_template_id_fkey';
            columns: ['template_id'];
            isOneToOne: false;
            referencedRelation: 'templates';
            referencedColumns: ['id'];
          },
        ];
      };
      templates: {
        Row: {
          active: boolean;
          category_slug: string | null;
          created_at: string;
          description: string | null;
          id: string;
          name: string;
          org_id: string;
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          category_slug?: string | null;
          created_at?: string;
          description?: string | null;
          id?: string;
          name: string;
          org_id: string;
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          category_slug?: string | null;
          created_at?: string;
          description?: string | null;
          id?: string;
          name?: string;
          org_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'templates_category_slug_fkey';
            columns: ['category_slug'];
            isOneToOne: false;
            referencedRelation: 'service_categories';
            referencedColumns: ['slug'];
          },
          {
            foreignKeyName: 'templates_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      threads: {
        Row: {
          client_handle: string | null;
          created_at: string;
          external_thread_id: string;
          id: string;
          job_id: string | null;
          last_message_at: string | null;
          org_id: string;
          platform: Database['public']['Enums']['platform'];
          redacted_at: string | null;
          status: Database['public']['Enums']['thread_status'];
          updated_at: string;
        };
        Insert: {
          client_handle?: string | null;
          created_at?: string;
          external_thread_id: string;
          id?: string;
          job_id?: string | null;
          last_message_at?: string | null;
          org_id: string;
          platform: Database['public']['Enums']['platform'];
          redacted_at?: string | null;
          status?: Database['public']['Enums']['thread_status'];
          updated_at?: string;
        };
        Update: {
          client_handle?: string | null;
          created_at?: string;
          external_thread_id?: string;
          id?: string;
          job_id?: string | null;
          last_message_at?: string | null;
          org_id?: string;
          platform?: Database['public']['Enums']['platform'];
          redacted_at?: string | null;
          status?: Database['public']['Enums']['thread_status'];
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'threads_job_id_fkey';
            columns: ['job_id'];
            isOneToOne: false;
            referencedRelation: 'jobs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'threads_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      usage_counters: {
        Row: {
          created_at: string;
          id: string;
          limit_value: number | null;
          metric: string;
          org_id: string;
          period_start: string;
          updated_at: string;
          used: number;
        };
        Insert: {
          created_at?: string;
          id?: string;
          limit_value?: number | null;
          metric: string;
          org_id: string;
          period_start: string;
          updated_at?: string;
          used?: number;
        };
        Update: {
          created_at?: string;
          id?: string;
          limit_value?: number | null;
          metric?: string;
          org_id?: string;
          period_start?: string;
          updated_at?: string;
          used?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'usage_counters_org_id_fkey';
            columns: ['org_id'];
            isOneToOne: false;
            referencedRelation: 'orgs';
            referencedColumns: ['id'];
          },
        ];
      };
      users: {
        Row: {
          auth_user_id: string | null;
          created_at: string;
          email: string | null;
          full_name: string | null;
          id: string;
          telegram_chat_id: string | null;
          updated_at: string;
        };
        Insert: {
          auth_user_id?: string | null;
          created_at?: string;
          email?: string | null;
          full_name?: string | null;
          id?: string;
          telegram_chat_id?: string | null;
          updated_at?: string;
        };
        Update: {
          auth_user_id?: string | null;
          created_at?: string;
          email?: string | null;
          full_name?: string | null;
          id?: string;
          telegram_chat_id?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      approval_channel: 'telegram' | 'web' | 'auto' | 'mcp';
      budget_type: 'fixed' | 'hourly';
      delivery_order_status:
        'draft' | 'assigned' | 'in_progress' | 'delivered' | 'accepted' | 'cancelled';
      delivery_route: 'in_house' | 'ai_build' | 'supplier' | 'source_new';
      estimate_method: 'in_house' | 'rate_card' | 'market_band' | 'candidate_quote' | 'ai_build';
      llm_outcome: 'ok' | 'invalid_output' | 'error';
      llm_purpose: 'score' | 'draft' | 'discovery' | 'brief' | 'estimate' | 'other';
      message_direction: 'in' | 'out';
      payment_direction: 'in' | 'out';
      payment_kind: 'client' | 'supplier' | 'platform_fee' | 'other_cost';
      pipeline_stage:
        | 'applied'
        | 'replied'
        | 'discovery'
        | 'briefed'
        | 'sourcing'
        | 'won'
        | 'in_delivery'
        | 'delivered'
        | 'paid'
        | 'lost';
      platform: 'freelancer' | 'upwork' | 'fiverr';
      platform_account_status: 'connected' | 'expired' | 'revoked' | 'error' | 'disconnected';
      portfolio_kind: 'own_work' | 'labelled_demo';
      price_band_source: 'seed' | 'marketplace_sample' | 'owner_csv' | 'completed_projects';
      proposal_status: 'draft' | 'queued' | 'approved' | 'rejected' | 'submitted' | 'failed';
      score_verdict: 'go' | 'caution' | 'skip';
      sourcing_post_status: 'draft' | 'approved' | 'posted' | 'closed' | 'failed';
      sourcing_status: 'open' | 'shortlisting' | 'chosen' | 'closed' | 'abandoned';
      supplier_channel: 'freelancer' | 'upwork' | 'fiverr' | 'direct' | 'in_house' | 'ai_build';
      thread_status: 'open' | 'awaiting_client' | 'awaiting_operator' | 'closed';
      user_role: 'owner' | 'operator' | 'viewer';
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type PublicSchema = Database['public'];

export type Tables<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Row'];
export type TablesInsert<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T]['Update'];
export type Enums<T extends keyof PublicSchema['Enums']> = PublicSchema['Enums'][T];

export const Constants = {
  public: {
    Enums: {
      approval_channel: ['telegram', 'web', 'auto', 'mcp'],
      budget_type: ['fixed', 'hourly'],
      delivery_order_status: [
        'draft',
        'assigned',
        'in_progress',
        'delivered',
        'accepted',
        'cancelled',
      ],
      delivery_route: ['in_house', 'ai_build', 'supplier', 'source_new'],
      estimate_method: ['in_house', 'rate_card', 'market_band', 'candidate_quote', 'ai_build'],
      llm_outcome: ['ok', 'invalid_output', 'error'],
      llm_purpose: ['score', 'draft', 'discovery', 'brief', 'estimate', 'other'],
      message_direction: ['in', 'out'],
      payment_direction: ['in', 'out'],
      payment_kind: ['client', 'supplier', 'platform_fee', 'other_cost'],
      pipeline_stage: [
        'applied',
        'replied',
        'discovery',
        'briefed',
        'sourcing',
        'won',
        'in_delivery',
        'delivered',
        'paid',
        'lost',
      ],
      platform: ['freelancer', 'upwork', 'fiverr'],
      platform_account_status: ['connected', 'expired', 'revoked', 'error', 'disconnected'],
      portfolio_kind: ['own_work', 'labelled_demo'],
      price_band_source: ['seed', 'marketplace_sample', 'owner_csv', 'completed_projects'],
      proposal_status: ['draft', 'queued', 'approved', 'rejected', 'submitted', 'failed'],
      score_verdict: ['go', 'caution', 'skip'],
      sourcing_post_status: ['draft', 'approved', 'posted', 'closed', 'failed'],
      sourcing_status: ['open', 'shortlisting', 'chosen', 'closed', 'abandoned'],
      supplier_channel: ['freelancer', 'upwork', 'fiverr', 'direct', 'in_house', 'ai_build'],
      thread_status: ['open', 'awaiting_client', 'awaiting_operator', 'closed'],
      user_role: ['owner', 'operator', 'viewer'],
    },
  },
} as const;
